# Introduction to numpy

__numpy array__ <br>
NumPy array is a data container. It is similar to Python lists, but it’s specialised for working on numerical data. NumPy is at the center of scientific Python ecosystem and it is a work-horse of many scientific libraries including scikit-learn, scikit-image, matplotlib, SciPy.

In general you should use this library if you want to do fancy things with **numbers**, especially if you have **matrices** or **arrays.** <br>

To use NumPy we need to start python interpreter and import numpy package:

In [14]:
import numpy as np

Let's create a simple numpy array

In [15]:
x = np.array([2, 1, 5])
print(x)

[2 1 5]


### Lists vs Numpy arrays

The Python core library provides Lists. A list is the Python equivalent of an array, but it is resizeable and can contain elements of different types.

Pros of an array:
 - **Size** - Numpy data structures take up less space
 - **Performance** - faster than lists
 - **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

To construct an array with pre-defined elements we can also use one of the built-in helper functions. <br>
__np.arange__ works like Python built-in range, but it returns an array; 

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

__np.ones__ and __np.zeros__ return arrays of 0s or 1s; 

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

__np.random.rand__ creates an array of random numbers from an interval [0, 1]:

In [19]:
np.random.rand(5)

array([0.74085304, 0.63461384, 0.86810264, 0.40038169, 0.56583529])

We can also construct a two- or more dimensional arrays:

In [20]:
np.array([[1, 2], [5, 6]])

array([[1, 2],
       [5, 6]])

In [21]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

Alternatively, a n-dimensional array can be obtained by reshaping a 1-D array:

In [22]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

One of the advantages of NumPy is that it allows to apply functions (called ufuncs) to all elements of an array without the need of `for` loops:

In [23]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

This is not only convenient but also more efficient than iterating through the elements using for loops.

[Previous: Index](index.ipynb)<br>[Next: Working with a dataset](dataset_intro.ipynb)